name: Publish NeoPaquet to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    name: Build distributions (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install build wheel setuptools

      - name: Build distribution
        run: python -m build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: neopaquet-${{ matrix.os }}
          path: dist/

  kali-build:
    name: Build on Kali Linux
    runs-on: ubuntu-latest
    container:
      image: kalilinux/kali-rolling
    steps:
      - uses: actions/checkout@v4

      - name: Install Python + build tools
        run: |
          apt-get update && apt-get install -y python3 python3-pip python3-venv build-essential
          python3 -m pip install --upgrade pip
          python3 -m pip install build wheel setuptools

      - name: Build distribution
        run: python3 -m build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: neopaquet-kali
          path: dist/

  pypi-publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: [build, kali-build]
    permissions:
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/project/neopaquet/

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/

      - name: Flatten artifacts
        run: |
          mkdir final-dist
          find dist -type f -exec mv {} final-dist/ \;

      - name: Publish distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: final-dist/
